version: '3.8'

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: steampals
      MARIADB_USER: steampals
      MARIADB_PASSWORD: steampalspass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/steampals
      SPRING_DATASOURCE_USERNAME: steampals
      SPRING_DATASOURCE_PASSWORD: steampalspass
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: always

volumes:
  db_data: